baseURL: "https://oleksandr-vlasov.com/"
languageCode: en-us
title: Oleksandr Vlasov
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40

params:
  profileMode:
    enabled: true
    title: "Oleksandr Vlasov"
    subtitle: Hi there! 👋 I’m Oleksandr. I’m a junior React Developer, just starting my journey in web development. I love creating interactive and user-friendly web apps. Right now, I’m learning all about React and its tools, like Redux for managing state, React Hooks for building reusable components, and React Native for mobile apps.
    imageUrl: "/me.jpeg"
    imageWidth: 220
    imageHeight: 220
    buttons:
      - name: Resume
        url: "https://drive.google.com/file/d/1WMarOb_wGE5xL-jhpGTOnhxRaey2gs7n/view?usp=sharing"

  socialIcons:
    - name: "email"
      url: "mailto:drumlife182@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/oleksandr-vlasov-9969ab19b/"
    - name: "github"
      url: "https://github.com/alexvlasov182"
    - name: "youtube"
      url: "https://www.youtube.com/@alexvlasov2271/videos"
