baseURL: "https://oleksandr-vlasov.com/"
languageCode: en-us
title: Oleksandr Vlasov
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    - identifier: experience
      name: Experience
      url: /experience
      weight: 40

markup:
  goldmark:
    renderer:
      unsafe: true

params:
  profileMode:
    enabled: true
    title: "Oleksandr Vlasov"
    subtitle: "Hi, I’m Oleksandr - a React & React Native Developer. I help startups and small teams build fast, reliable MVPs for web and mobile platforms. I specialize in cross-platform apps with React Native, scalable UIs with Next.js & TypeScript, and expanding backend skills with Node.js and Go. I enjoy writing clean code, working in agile teams, and adapting quickly to new challenges."
    imageUrl: "/home/me.jpeg"
    imageWidth: 220
    imageHeight: 220
    buttons:
      - name: Resume
        url: "https://drive.google.com/file/d/1RrDBoqQdozzbUff6ScINM0qrZl6sj2-3/view?usp=sharing"


  socialIcons:
    - name: "email"
      url: "mailto:drumlife182@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/oleksandr-vlasov-9969ab19b/"
    - name: "github"
      url: "https://github.com/alexvlasov182"
    - name: "youtube"
      url: "https://www.youtube.com/@alexvlasov2271/videos"
